---
title: "Aula 1"
author: "humberto serna"
date: "1SEM2022"
output: slidy_presentation
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Apresentação


-   Aulas Expositivas intercaladas à prática.

-   Exercícios serão sugeridos para resolução em casa. Não é preciso
    entregá-los, mas encorajamos trazer dúvidas.






## A linguagem R

-   Criada por **R**oss Ihaka e por **R**obert Gentleman da Universidade de Auckland.

-   Originalmente criada por estatísticos para estatísticos, incorporou outros usos.

-   É facilmente extensível através de funções e bibliotecas.

-   Código aberto recebe intervenção da comunidade de colaboradores no código fonte da linguagem e criação de bibliotecas.

-   Mantida pelo *R Core Team*, fazendo a divulgação das versões oficiais






## Apresentando o Rgui

-   É o ambiente de programação da Linguagem R: interpretador +
    interface de usuário.

-   Instalando o R: <https://cran.r-project.org/bin/windows/base/>







## Rconsole

-   O sinal **\>** (sinal de maior) indica o prompt e significa que ele está pronto para receber comandos

-   Acessando a ajuda do R:

    -   abrindo a documentação de uma função/comando: `help("sum")` ou `?sum`

    -   buscando por palavra: `help.search("sum")` ou `??sum`

-   A comunidade de usuários é muito colaborativa e engajada:
    -   Stackoverflow: <https://pt.stackoverflow.com/>
    -   Discourse Curso-R: <https://discourse.curso-r.com/>
    -   R-Bloggers: <https://www.r-bloggers.com/>
    -   E muito mais

- consultando a versão`version`, `q()` 



## Uso mais elementar: calculadora científica

-   operações aritméticas
-   armazenamento de variável (*case-sensitive*)
    + operador de atribuição:  `<-`
-   operações com variáveis
-   funções matemáticas:\
    `sum(), prod(), exp(), log(), sqrt(), sample(), mean(), etc..`
    
> Exercício: crie uma variável chamada **banana** e atribua a ela o valor 12; Crie outra chamada **laranja** com valor 6. Agora some banana com laranja. 

use o comando `seq()` para criar sequência dos números ímpares entre 1 e 100 (dica: consulte a documentação dessa função)






## Uso mais elementar: calculadora científica

-   Gerando Sequências
    -   ordenadas: `1:10` ou `seq(1,100)`
    -   com repetições: `rep(1:3,10)`
    
> Exercício: use o comando `seq()` para criar sequência dos números ímpares entre 1 e 100 (dica: consulte a documentação dessa função)


-   combinando valores: 

```
   conjunto_A <- c(1:5,10:15)
```
-   Acessando valores  

```
> conjunto_A[x]
```

-   Listando e excluindo variáveis:

```
    > ls()

    > rm()
```






## Apresentando o Rstudio

-   Uma IDE (ambiente de desenvolvimento integrado), simplificando o
    processo de escrever códigos

-   sugestão de autocompletar, destaque por cores

-   Download e instalação:
    <https://www.rstudio.com/products/rstudio/download/>






## Tipos de dados: numeric, integer, double, character e logical

-   O tipo de dado (classe de um objeto)

```
    > class(conjunto_A <- c(1:5,10:15))
    [1] "integer"
```
-   integer e double para números/quantidades

```
    num <- as.numeric(1:1000)
    dbl <- as.double(1:1000)
    int <- as.integer(1:1000)

    # Doubles são ~2x maiores
    > object.size(dbl)
    8048 bytes
    > object.size(int)
    4048 bytes
    > object.size(num)
    8048 bytes
```






## Tipos de dados: character e logical

-   *character* usamos para textos

```
    planeta_1 <- "mercúrio"
```

-   Porém ocupa mais espaço de armazenamento. Procure manter seu uso para texto.

```
      > pi_char <- "3.1416"
      > pi_num <- pi
      > object.size(pi_char)
      112 bytes
      > object.size(pi_num)
      56 bytes

```
      
-   Há casos particulares: CPFs que começam com zero, subclasses CNAE, CEP (ZIP code), etc. Requer atenção.

## Tipos de dados: character e logical

-   *logical* armazena os "valores" TRUE ou FALSE

```
    > 1 == "1"

    conjunto <- c(5, 4, 2, 1, 9, 1, 2.5)
    conjunto > 3
    
```    
- Testes lógicos com os operadores 
  - `==` 
  - `!=` 
  - `>=` `<=` 
  - `|` 


## Vetores e Coerção

-     São conjuntos indexados de valores: seus valores tem um atributo de posição
-     Basta colocar os valores separados por vírgulas dentro de um c().
-     Só pode ter uma classe de objeto dentro dele. Quando misturamos tipos de dados dentro de um vetor o R impõe a mesma classe a todos, é a **Coerção**
-     **Coerção**: classes mais fracas serão reprimidas por mais fortes (`character` tem primazia)
-     Vetor de caracteres?



## Exercícios


1. Escreva um programa em R para receber a entrada do usuário (nome e idade) e exibir os valores. Imprima também a versão da instalação do R. 

2. Escreva um programa em R para obter os detalhes dos objetos na memória. 

3. Escreva um programa em R para criar uma sequência de números de 20 a 50 e encontre a média dos números de 20 a 60 e a soma dos números de 51 a 91. 

4. Escreva um programa R para criar um vetor que contenha 10 valores inteiros aleatórios entre -50 e +50. (dica: use sample())


